version: '3.2'

services:
    php:
        image: smirik/resonances-web
        volumes:
            - log:/var/log/nginx
        depends_on:
            - db
        expose:
            - "8080"
        working_dir: /var/www/html
        environment:
            APP_ENV: "prod"
            WEB_PORTS: "80 443"
            VIRTUAL_HOST: "resonances.local"
            VIRTUAL_PORT: 8080
        networks:
            - backend
    web:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        environment:
            - DEFAULT_HOST=resonances.local
        networks:
            - backend

    watchtower:
        image: v2tec/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 300
    db:
        image: mysql:5.5
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        networks:
            - backend

volumes:
    db:
    log:

networks:
    backend:
