version: '3.2'

services:
    php:
        build:
            context: ./config/docker/php
            args:
                - HOST_UID=${HOST_UID}
        depends_on:
            - db
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        entrypoint: ./config/docker/php/docker-entrypoint.sh
        environment:
            - COMPOSER_HOME=/var/www/html/var/composer
            - PHP_IDE_CONFIG
            - APP_ENV
    nginx:
        image: 4xxi/nginx:flex
        depends_on:
            - php
        ports:
            - "${EXTERNAL_HTTP_PORT}:80"
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
    db:
        image: mysql:5.5
        ports:
            - "${DB_EXTERNAL_PORT}:3306"
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
volumes:
    db:
